// Author:      Alberto Salmerón Moreno <salmeron@lcc.uma.es>
// Copyright:   Copyright 2016-2021 Universidad de Málaga (University of Málaga), Spain
//
// This file is part of the TRIANGLE project. The TRIANGLE project is funded by the European Union’s
// Horizon 2020 research and innovation programme, grant agreement No 688712. [2016 - 2018]

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tap.Plugins.UMA.Android.Instruments
{
    /// <summary>
    /// The result of executing an adb command
    /// </summary>
    public class AdbCommandResult
    {
        /// <summary>
        /// <c>True</c> if the command finished successfully; <c>false</c> otherwise
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// The output lines generated by the command, combining both standard output and standard error
        /// </summary>
        public List<string> Output { get; set; }
    }
}
